name: ci

on:
  push:
    branches:
      - develop
      - main
      - release/*
  pull_request:
    branches:
      - develop
      - main
      - release/*

jobs:
  build_and_run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang, msvc]
        preset_build_type : [debug, release]
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
          - os: windows-latest
            compiler: msvc
        exclude:
          - os: ubuntu-latest
            compiler: msvc
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Configure project
      run: cmake --preset ${{ matrix.preset_build_type }}-${{ matrix.compiler }}

    - name: Build project
      run: cmake --build --preset ${{ matrix.preset_build_type }}-${{ matrix.compiler }}

    - name: Run executables
      shell: bash
      run: |
        for f in ./build/${{ matrix.preset_build_type }}-${{ matrix.compiler }}/bin/*; do
          if [[ -f "$f" ]]; then
            "$f"
          fi
        done

  clang_format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Configure project
      run: cmake --preset clang-format

    - name: Build project and check code formatting with clang-format
      run: cmake --build --preset clang-format-check

  clang_tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Configure project
      run: cmake --preset clang-tidy

    - name: Build project and run code static analysis with clang-tidy
      run: cmake --build --preset clang-tidy

  sanitizer:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        sanitize: [address, leak, memory, thread, undefined]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Configure project
      run: cmake --preset sanitizer-${{ matrix.sanitize }}

    - name: Build project
      run: cmake --build --preset sanitizer-${{ matrix.sanitize }}

    - name: Run executables
      shell: bash
      run: |
        for f in ./build/sanitizer-${{ matrix.sanitize }}/bin/*; do
          if [[ -f "$f" ]]; then
            "$f"
          fi
        done

  doxygen:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    - name: Configure project
      run: cmake --preset doxygen

    - name: Build project and run doxygen
      run: cmake --build --preset doxygen

  cmake_format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake-format

    - name: Configure project
      run: cmake --preset cmake-format

    - name: Build project and check CMake code formatting with cmake-format
      run: cmake --build --preset cmake-format-check

  cmake_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake-format

    - name: Configure project
      run: cmake --preset cmake-lint

    - name: Build project and check CMake code with cmake-lint
      run: cmake --build --preset cmake-lint
